FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build 
# Stage 2: Serve the React application with NGINX
FROM nginx:alpine

# Copy the custom NGINX configuration file
# This file defines how NGINX will serve your React app and handle routes.
COPY nginx.conf /etc/nginx/conf.d/default.conf 
# Remove default NGINX index.html to avoid conflicts
RUN rm -rf /usr/share/nginx/html/*

# Copy the built React application files to NGINX's web root
# Assuming 'npm run build' outputs to a 'dist' directory, adjust if it's 'build' or something else
COPY --from=build /app/dist /usr/share/nginx/html

# Expose port 80, as NGINX listens on 80
EXPOSE 80

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]

