# Stage 1: Build the React application
FROM node:18 as build

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

# This command generates the static React app files into the 'dist' folder
RUN npm run build

# Stage 2: Serve the React application with NGINX
FROM nginx:alpine

# Copy the custom NGINX configuration file
COPY nginx.conf /etc/nginx/conf.d/default.conf

# Remove default NGINX index.html to avoid conflicts
RUN rm -rf /usr/share/nginx/html/*

# Copy the built React application files from the 'dist' folder to NGINX's web root
COPY --from=build /app/build /usr/share/nginx/html

# Expose port 80, as NGINX listens on 80
EXPOSE 80

# Command to run NGINX in the foreground
CMD ["nginx", "-g", "daemon off;"]
