apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/nimsara2000/mern-backend:latest
          ports:
            - containerPort: 5000
          env:
            - name: SECRET_KEY
              value: "KIRTI12345"
            - name: CONNECTION_STRING
              value: "mongodb://mongo:27017/foodRecipe"