apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag | default "latest" }}
          ports:
            - containerPort: 3000
          env:
            - name: SECRET_KEY
              value: "KIRTI12345"
            - name: CONNECTION_STRING
              value: "mongodb://mongo:27017/foodRecipe"