backend:
  image: nimsara2000/mern-backend:latest # <-- Replace with your Docker Hub image if you have one
  replicaCount: 1
  port: 5000
  env:
    SECRET_KEY: "KIRTI12345"
    CONNECTION_STRING: "mongodb://mongo:27017/foodRecipe"

frontend:
  image: nimsara/mern-frontend:latest # <-- Replace with your Docker Hub image if you have one
  replicaCount: 1
  port: 80

mongo:
   image: mongo:6
   replicaCount: 1
   port: 27017
